# Generated by Django 5.0.4 on 2024-05-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='articles_read',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
