# Generated by Django 5.0.4 on 2024-04-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(default='default.png', upload_to='outlet_logos')),
            ],
        ),
        migrations.CreateModel(
            name='Blurb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('link', models.CharField(max_length=255)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='features.outlet')),
            ],
        ),
    ]
