# Generated by Django 5.0.4 on 2024-04-17 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_blurb_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_blurbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blurb',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_blurbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outlet',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='logo',
            field=models.ImageField(default='images/default.png', upload_to='outlet_logos'),
        ),
    ]
