# Generated by Django 5.0.4 on 2024-04-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_blurb_downvotes_blurb_upvotes_outlet_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='page_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
