# Generated by Django 5.0.4 on 2024-05-06 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_alter_comment_author_alter_comment_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blurb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='features.blurb'),
        ),
    ]
