# Generated by Django 5.0.4 on 2024-05-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_alter_comment_blurb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
