# Generated by Django 5.0.4 on 2024-05-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='tags',
            field=models.ManyToManyField(blank=True, to='features.tag'),
        ),
    ]
